version: "3.5"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    hostname: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    networks:
      - net01
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka_00:
    image: docker.io/bitnami/kafka:3.2
    hostname: kafka_00
    ports:
      - "9092:9092"
      - "9093:9193"
    volumes:
      - "kafka_data:/bitnami"
    networks:
      - net01
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093,INTERNAL://:9193
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka_00:9092,EXTERNAL://localhost:9093,INTERNAL://kafka_00:9193
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  kafka_01:
    image: docker.io/bitnami/kafka:3.2
    hostname: kafka_01
    ports:
      - "9192:9092"
      - "9193:9093"
    volumes:
      - "kafka_data_01:/bitnami"
    networks:
      - net01
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9193,INTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka_01:9092,EXTERNAL://localhost:9193,INTERNAL://kafka_01:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  kafka_02:
    image: docker.io/bitnami/kafka:3.2
    hostname: kafka_02
    ports:
      - "9292:9092"
      - "9293:9093"
    volumes:
      - "kafka_data_02:/bitnami"
    networks:
      - net01
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9293,INTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka_02:9092,EXTERNAL://localhost:9293,INTERNAL://kafka_02:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  kafka_data_01:
    driver: local
  kafka_data_02:
    driver: local

networks:
  net01:
    name: common_network
    driver: bridge